/**
 * Property Module Lifecycle Workflow States and Allowed Transitions
 */

export const PROPERTY_STATUS = {
  DRAFT: 'draft',
  PENDING_REVIEW: 'pending_review',
  PUBLISHED: 'published',
  ARCHIVED: 'archived',
  REJECTED: 'rejected',
  SUSPENDED: 'suspended',
  SOFT_DELETED: 'soft_deleted',
  EXPIRED: 'expired'
};

export const ALLOWED_TRANSITIONS = {
  [PROPERTY_STATUS.DRAFT]: [PROPERTY_STATUS.PENDING_REVIEW, PROPERTY_STATUS.SOFT_DELETED],
  [PROPERTY_STATUS.PENDING_REVIEW]: [PROPERTY_STATUS.PUBLISHED, PROPERTY_STATUS.REJECTED, PROPERTY_STATUS.SOFT_DELETED],
  [PROPERTY_STATUS.PUBLISHED]: [PROPERTY_STATUS.ARCHIVED, PROPERTY_STATUS.SUSPENDED, PROPERTY_STATUS.EXPIRED, PROPERTY_STATUS.SOFT_DELETED],
  [PROPERTY_STATUS.ARCHIVED]: [PROPERTY_STATUS.DRAFT, PROPERTY_STATUS.PUBLISHED, PROPERTY_STATUS.SOFT_DELETED],
  [PROPERTY_STATUS.REJECTED]: [PROPERTY_STATUS.DRAFT, PROPERTY_STATUS.SOFT_DELETED],
  [PROPERTY_STATUS.SUSPENDED]: [PROPERTY_STATUS.PUBLISHED, PROPERTY_STATUS.SOFT_DELETED],
  [PROPERTY_STATUS.SOFT_DELETED]: [PROPERTY_STATUS.DRAFT, PROPERTY_STATUS.ARCHIVED], // Allowed recovery paths
  [PROPERTY_STATUS.EXPIRED]: [PROPERTY_STATUS.DRAFT, PROPERTY_STATUS.PUBLISHED, PROPERTY_STATUS.SOFT_DELETED]
};

export const isValidTransition = (current, target) => {
  if (!current) return true; // Initial creation
  const allowed = ALLOWED_TRANSITIONS[current] || [];
  return allowed.includes(target);
};
